source 'https://rubygems.org'
gem 'json'
gem 'net-http-persistent', '~> 2.9'
gem 'sqlite3'
gem 'telegram-bot-ruby'
gem 'minitest'
gem 'minitest-reporters'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-performance'